version: "3"

services:
  spigot:
    build: .
    cap_drop:
      - ALL
    ports:
      - 25565:25565
    tty: true
    stdin_open: true
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "1"
    volumes:
      - ./server/:/server/